#lang scheme

(define d 0)
(define m 0) 
(define a 0)
(define b 0)
(display "Inserte el día: ")
(set! d (read))
(display "Inserte el mes: ")
(set! m (read))
(display "Inserte el año: ")
(set! a (read))
(if(and(=(remainder a 4)0)(or(not(=(remainder a 100)0))(=(remainder a 400)0)))
   (set! b 1)
   (set! b 0)
   ); Función bisiesto
(if(or(= m 1)(= m 3)(= m 5)(= m 7)(= m 8)(= m 10))
    (if(= d 31) 
             (begin(set! d 1)
                   (set! m (+ m 1)))
             (set! d (+ d 1)))
    (if (and(= m 2)(= b 1))
        (if(= d 29)
           (begin(set! d 1)
                 (set! m (+ m 1))
                 )
           (set! d (+ d 1)))
           (if(and(= m 2)(= b 0))
              (if(= d 28)
                 (begin(set! d 1)
                       (set! m (+ m 1))
                 )
                 (set! d (+ d 1))
                 )
    (if (= m 12)
        (if (= d 31)
           (begin(set! d 1)
                 (set! m 1)
                 (set! a (+ a 1)))
                 
           (set! d (+ d 1)))
        (if (= d 30)
            (begin(set! d 1)
                 (set! m (+ m 1)))
                 (display "mucha condición")
                 )))))
(display "La fecha de mañana es: ")(display d)(display "/")(display m)(display "/")(display a)