#lang racket/gui
(define j1 "")
(define j2 "")
(define vida 100)
(define vida2 100)
(define ronda 1)
(define d1 0)
(define cont 0)
(define d2 0)
(define (primeraInt) ; Para nombrar personajes
  (define dialog (instantiate dialog% ("Juego")))
  (define panel (new horizontal-panel% [parent dialog]
                                     [alignment '(center center)]))
  (new button% [parent panel] [label "Nombrar jugador dos"])
(new button% [parent panel] [label "Nombrar jugador uno"])
(when (system-position-ok-before-cancel?)
  (send panel change-children reverse))
  (send dialog show #t)
  (define ((make-check i) btn evt)
  (message-box "." )
    )
  (display "inserte nombre del primer jugador: ")
  (set! j1 (read))
  (display "inserte nombre del segundo jugador: ")
  (set! j2 (read))
  (juego)
  )
(define (rondas); Avance de rondas
  (set! ronda (+ ronda 1))
  )
(define (aleatoreidad) ;Para daños, críticos y fallas
(set! d1 (random 1 11))
(set! d2 (random 1 11))
  )
(define (dañoj2)
  (if(not(= d1 d2))
     (begin
            (display j2)
            (display " golpea a ")
            (display j1)
            (display " haciendo 10 de daño! \n")
            (set! vida (- vida 10))
            )
     (begin
       (display j2)
       (displayln " Falló")
       )
     )
  )
(define (dañoj1)
  (if(not(= d1 d2))
     (begin
            (display j1)
            (display " golpea a ")
            (display j2)
            (display " haciendo 10 de daño! \n")
            (set! vida2 (- vida2 10))
            )
     (begin
       (display j1)
       (displayln " Falló")
       )
     )
  )
(define (juego)
  (display "La ronda es: ")(displayln ronda)
  (cond
     [(= vida 0)(display "\n Gana: ")(display j2)]
     [(= vida2 0)(display "\n Gana: ")(display j1)]
     (else
      (aleatoreidad)
      (dañoj1)
      (aleatoreidad)
      (dañoj2)
      (rondas)
      (display "0 para continuar, 1 para salir ")
      (set! cont (read))
      (if(= cont 0)
         (juego)
         (display "¡Gracias por jugar!")
         )
      )
     )
  )
(primeraInt)
  
  