#lang racket
(define (cuenta-cadenas lista cadena canti-repe contador)
  (if (= contador (length lista))
         (begin
           (display "The total elements of ")
           (display cadena)
           (display " is ")
           (display canti-repe)
           )
  (if (equal? (list-ref lista contador) cadena)
      (cuenta-cadenas lista cadena (+ canti-repe 1) (+ contador 1))
      (cuenta-cadenas lista cadena canti-repe (+ contador 1))
      )
  )
  )
(display "Insert the list you want to evaluate: ")
(define lista (read))
(display "Insert the number you want to evaluate: ")
(define cadena (read))
(cuenta-cadenas lista cadena 0 0)