#lang racket
(define (registrar posicion lista-final)
  (display "Insert the student's code: ")
  (define codigo (read))
  (newline)
  (display "Insert the student's name: ")
  (define nombre (read))
  (newline)
  (display "Insert the program of the student: ")
  (define programa (read))
  (set! lista-final (append lista-final (list(list codigo nombre programa))))
  (interfaz posicion lista-final)
  )
(define (buscar-estudiante codigo lista-estudiantes)
  (define (buscar codigo estudiante)
    (cond
      ((null? estudiante) "The student isn't registered!")
      ((equal? codigo (list-ref estudiante 0)) (list (list-ref estudiante 1) (list-ref estudiante 2)))
      (else (buscar codigo (rest estudiante)))))
  (cond
    ((null? lista-estudiantes) "The student isn't registered!")
    (else (buscar codigo (car lista-estudiantes))))) 

(define (interfaz posicion lista-final)
  (displayln "What do you want to do?")
  (display "1) Register a student \n2) Search a student by his code in the system")
  (define opc (read))
  (if (= opc 1)
      (registrar posicion lista-final)
      (if (= opc 2)
          (begin
            (display "Insert his code: ")
            (displayln (buscar-estudiante (read) lista-final))
            (retorno posicion lista-final)
            )
          (begin
            (display "That's not an option, try again.")
            (interfaz posicion lista-final)
            )
          )
      )
  )
(define (retorno posicion lista-final)
  (displayln "Do you want to go back?")
  (displayln "1) Yes \n2) No")
  (define opc (read))
  (cond
    ((= opc 1)(interfaz posicion lista-final))
    ((= opc 2)(void))
    (else (display "That's not an option, try again")
          (retorno))
    )
  )
(interfaz 0 '())