#lang racket
(define (igual? lista1 lista2 contador)
  (if (= (length lista1)(length lista2))
      (if(= (length lista1) contador)
         (display "Both lists are the same!")
         (if (= (list-ref lista1 contador)(list-ref lista2 contador))
             (igual? lista1 lista2 (+ contador 1))
             (display "Both lists are different!")
             )
         )
      (display "Both lists are different!")
      )
  )
(display "Insert the first list: ")
(define lista1 (read))
(display "Insert the list you want to compare with: ")
(define lista2 (read))
(igual? lista1 lista2 0)