#lang racket
(define (ej1)
  ; Números del 10 al 1
  (define n 10)
  (define (funPrin)
    (if (= n 1)
        (display n)
        (begin(displayln n)
              (set! n (- n 1))
              (funPrin)
              )
        )
    )
  (funPrin)
  )
;__________________________________________________
(define (ej2)
  ; Números del 1 al 10
  (define n 1)
  (define (funPrin)
    (if (= n 10)
        (display n)
        (begin(displayln n)
              (set! n (+ n 1))
              (funPrin)
              )
        )
    )
  (funPrin)
  )
;____________________________________________________
(define (ej3)
  ; Cubos, cuadrados, raices, etc
  (define (operaciones x)
    (display ", cuadrado: ")
    (display(expt n 2))
    (display ", cubo: ")
    (display(expt n 3))
    (display ", raiz cuadrada: ")
    (display(sqrt n))
    (display ", raíz cúbica: ")
    (displayln(expt n (/ 1 3)))
    )
    (define n 10)
  (define (funPrin)
    (if (= n 100)
        (begin
          (display n)
          (operaciones n)
          )
        (begin
          (display n)
          (operaciones n)
          (set! n (+ n 1))
          (funPrin)
          )
        )
  )
  (funPrin)
)
;____________________________________________________
(define (ej4)
  ; SUMA DE LOS PRIMEROS 10 NÚMEROS
  (define n 0)
  (define suma 0)
  (define (funPrin n)
    (if(>= n 10)
       (begin(set! suma (+ suma n)) ; #t
             (display suma)
             )
       (begin (set! suma (+ suma n)) ; #f
              (set! n (+ n 1))
              (funPrin n)
              )
       )
    )
  (define (interfaz)
    (displayln "Suma de los primeros 10 números:")
    (funPrin n)
    )
  (interfaz)
  )
;____________________________________________________
(define (ej5)
   ; SUMA DE LOS PRIMEROS 100 NÚMEROS
  (define n 0)
  (define suma 0)
  (define (funPrin n)
    (if(>= n 100)
       (begin(set! suma (+ suma n)) ; #t
             (display suma)
             )
       (begin (set! suma (+ suma n)) ; #f
              (set! n (+ n 1))
              (funPrin n)
              )
       )
    )
  (define (interfaz)
    (displayln "Suma de los primeros 100 números:")
    (funPrin n)
    )
  (interfaz)
  )
;_____________________________________________________
(define (ej6)
  ; suma de números menores
  (define n1 (read))
  (define suma 0)
  (define n 0)
  (define (funPrin)
    (if(= n n1)
       (display suma)
       (begin(set! suma (+ n suma))
             (set! n (+ n 1))
             (funPrin)
             )
       )
    )
  (funPrin)
  )
;_____________________________________________________
(define (ej7)
  ; Suma de cuadrados
  (define m 0)
  (define n 0)
  (set! m (read))
  (set! n (read))
  (define suma 0)
  (define (funPrin)
    (if(= n m)
       (display suma)
    (begin(set! suma (+ (expt n 2) suma))
          (set! n (+ n 1))
          (funPrin)
          )
    )
    )
  (funPrin)
  )
; después de hacer estos ejercicios me quedan algunas dudas, enviaré adelanto del trabajo, más no es el definitivo.